import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                {["ch0", "ch1", "ch2", "ch3"].map((chNumber) =>
                    <div className={styles.card} key={chNumber}>
                        <video className={styles.video} controls preload="none" autoPlay>
                            <source src={`http://localhost:8080/stream/${chNumber}/index.m3u8`}
                                    type="application/x-mpegURL"/>
                        </video>
                    </div>
                )}

            </main>
        </div>
    )
}

export default Home
